config/routes.rb
Rails.application.routes.draw do
  resources :box_owners
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  post 'ajax_post', to: 'box#ajax_post'
  post 'attach_box_owner', to: 'box#attach_box_owner'
  delete 'ajax_delete', to: 'box#ajax_delete'

  resources :box
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/box.rb
require "#{Rails.root}/lib/encryption_wrapper"

class Box < ApplicationRecord
  belongs_to :box_owner, optional: true
  # TODO: One Box's field is a label; It's currently being stored in plain text and we would like to encrypt it using the AWS KMS SDK
  # See more info here: https://docs.aws.amazon.com/sdk-for-ruby/v3/developer-guide/kms-example-encrypt-data.html
  # You can find the required credentials in the README.md
  # Implemented! With EncryptionWrapper

  validates :label, :size, presence: true

	# To encrypt with  AWS KMS SDK from class EncryptionWrapper in lib/encryption_wrapper.rb
  include EncryptionWrapper

  # To cast label as Encrypt type
  # If wants check encrypted value in console can run Box.first.label_before_type_cast
	serialize :label, EncryptionWrapper.new

end

app/models/box_owner.rb
require "#{Rails.root}/lib/encryption_wrapper"

class BoxOwner < ApplicationRecord

  validates :first_name, :last_name, :email, presence: true

  include EncryptionWrapper

  # To cast email as Encrypt type
  # If wants check encrypted value in console can run BoxOwner.first.email_before_type_cast
	serialize :email, EncryptionWrapper.new
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #TODO: Implement the `Box Owner` features described in the README Implement 
  # with box_owners_controller created with 'rails g scaffold'
end

app/controllers/box_controller.rb
class BoxController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:ajax_post, :ajax_delete, :attach_box_owner, :update]

  def index
    @boxes = Box.all.order(id: :desc)
    @box_owners = BoxOwner.all.order(id: :desc).map {|o| {value: o.id, label: o.email} }
  end

  def new
    
  end

  def create

  end

  def update
    # TODO: Add Box Update logic; Users should only be able to update the label (but not the size)
    # Implement!
    label = params[:label]
    id = params.require(:id)
    begin
      if Box.find(id).update(label: label)
        render json: {success: true}
      end
    rescue Exception => e
      render json: {success: false, error: e.message}
    end
  end

  def show

  end

  def edit

  end

  def destroy

  end

  def attach_box_owner
    box_owner = params[:box_owner]
    id = params[:box].require(:id)
    begin
      if Box.find(id).update(box_owners_id: box_owner)
        render json: {success: true}
      end
    rescue Exception => e
      render json: {success: false, error: e.message}
    end
  end

  def ajax_post
    size = params[:size]
    label = params.require(:label)
    open = params.require(:open)
    if Box.create({size: size, label: label, open: open})
      render json: {success: true}
    else
      render json: {success: false, error: e.message}
    end
  end

  def ajax_delete
    id = params.require(:id)

    if Box.find(id).destroy
      render json: {success: true}
    else
      render json: {success: false}
    end
  end
end

app/controllers/box_owners_controller.rb
class BoxOwnersController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:create, :destroy]
  
  before_action :set_box_owner, only: %i[ show edit update destroy ]

  # GET /box_owners or /box_owners.json
  def index
    @box_owners = BoxOwner.all.order(id: :desc)
  end

  # GET /box_owners/1 or /box_owners/1.json
  def show
  end

  # GET /box_owners/new
  def new
  end

  # GET /box_owners/1/edit
  def edit
  end

  # POST /box_owners or /box_owners.json
  def create
    @box_owner = BoxOwner.new(box_owner_params)

    if @box_owner.save!
      render json: {success: true}
    else
      render json: {success: false, error: e.message}
    end
  end

  # PATCH/PUT /box_owners/1 or /box_owners/1.json
  def update
    
  end

  # DELETE /box_owners/1 or /box_owners/1.json
  def destroy
    if @box_owner.destroy
      render json: {success: true}
    else
      render json: {success: false}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box_owner
      @box_owner = BoxOwner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def box_owner_params
      params.require(:box_owner).permit(:first_name, :last_name, :email, :box_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/box_helper.rb
module BoxHelper
end

app/helpers/box_owners_helper.rb
module BoxOwnersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/box/index.html.erb
<div class="principal_container">
	<%= react_component("BoxList", {boxes: @boxes, total: @boxes.size, box_owners: @box_owners}) %>
</div>

app/views/box/new.html.erb
<div class="principal_container">
	<%= react_component("BoxForm", {size: 'no_selection', label: ''}) %>
</div>

app/views/box_owners/index.html.erb
<div class="principal_container">
	<%= react_component("BoxOwnerList", {box_owners: @box_owners, total: @box_owners.size}) %>
</div>

app/views/box_owners/new.html.erb
<div class="principal_container">
	<%= react_component("BoxOwnerForm", {first_name: '', last_name: '', email: ''}) %>
</div>

app/views/home/index.html.erb
<!--<h1>The Box Factory</h1>

<%= react_component("Box", {size: 'large', label: 'We offer many boxes!'}) %>

<style type="text/css">
* {
  color: black;
  font-family: 'Courier New', Courier, monospace;
}
</style-->

<%= react_component("BoxHome", {label: 'Welcome to The Box Factory!'}) %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="bg-light text-lg-start">
  <!-- Grid container -->
  <div class="container p-4">
    <!--Grid row-->
    <div class="row">
      <!--Grid column-->
      <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase footer_txt_color">The Box Factory</h5>

        <p>
          Lacus luctus accumsan tortor posuere ac ut consequat semper. Urna neque viverra justo nec. Fusce id velit ut tortor pretium viverra suspendisse potenti nullam. Volutpat blandit aliquam etiam erat.
        </p>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Pages</h5>

        <ul class="list-unstyled mb-0">
          <li>
            <a href="#!" class="">About Us</a>
          </li>
          <li>
            <a href="#!" class="">Careers</a>
          </li>
          <li>
            <a href="#!" class="">Pricing</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!" class="">Twitter</a>
          </li>
          <li>
            <a href="#!" class="">Facebook</a>
          </li>
        </ul>
      </div>
      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <!--div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div-->
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar navbar-static-top navbar-expand-md">
  <div class="container">
    <button type="button" class="navbar-toggler collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only"><%= image_pack_tag "media/components/images/box_logo.png" %>THE BOX FACTORY</span>
    </button> 
    <div class="text-nav"><%= image_pack_tag "media/components/images/box_logo.png" %> <span>THE BOX FACTORY</span></div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to "Boxes", box_index_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Box", new_box_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Box Owners", box_owners_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New Box Owner", new_box_owner_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>The Box Factory</title>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- TODO: Should move the inline CSS to a css file  Implemented! Moved to index.css-->

  </head>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <body>
    <div>
      <%= yield %>
    </div>
  </body>
  <%= render 'layouts/footer' %>
</html>